version: "3.9"

services:
  sms-app:
    container_name: sms-app
    build:  # delete this build section for Portainer
      context: .
      dockerfile: Dockerfile
    image: telnyx_sms_app:${APP_VERSION}
    env_file:
      - .env  # For Portainer use stack.env
    ports:
      - "8400:8000"  # External 8400 -> Internal 8000
    volumes:
      - telnyx-sms-data:/app/data  # Named volume
    networks:
      - telnyx-sms-net
    restart: unless-stopped

volumes:
  telnyx-sms-data:

networks:
  telnyx-sms-net:
    driver: bridge
